// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAuLB_TmUKS3qGLNRIdqYc_KcCs_Cpfxs',
    appId: '1:740586991744:web:e4010514049483213d7665',
    messagingSenderId: '740586991744',
    projectId: 'medilearn-notifications-dd32b',
    authDomain: 'medilearn-notifications-dd32b.firebaseapp.com',
    storageBucket: 'medilearn-notifications-dd32b.firebasestorage.app',
    measurementId: 'G-N0BZPNB3HB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr3kGv-pjpYKhSO7Rdy9296y4XyN_AN-c',
    appId: '1:740586991744:android:5ed0debb5be916d13d7665',
    messagingSenderId: '740586991744',
    projectId: 'medilearn-notifications-dd32b',
    storageBucket: 'medilearn-notifications-dd32b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcgx5yR--eePyMpIdzMHAV6twOxTlQERg',
    appId: '1:740586991744:ios:9ca0fac467e121393d7665',
    messagingSenderId: '740586991744',
    projectId: 'medilearn-notifications-dd32b',
    storageBucket: 'medilearn-notifications-dd32b.firebasestorage.app',
    iosBundleId: 'com.example.medLearningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcgx5yR--eePyMpIdzMHAV6twOxTlQERg',
    appId: '1:740586991744:ios:9ca0fac467e121393d7665',
    messagingSenderId: '740586991744',
    projectId: 'medilearn-notifications-dd32b',
    storageBucket: 'medilearn-notifications-dd32b.firebasestorage.app',
    iosBundleId: 'com.example.medLearningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAuLB_TmUKS3qGLNRIdqYc_KcCs_Cpfxs',
    appId: '1:740586991744:web:003c6c82ad6a7ed23d7665',
    messagingSenderId: '740586991744',
    projectId: 'medilearn-notifications-dd32b',
    authDomain: 'medilearn-notifications-dd32b.firebaseapp.com',
    storageBucket: 'medilearn-notifications-dd32b.firebasestorage.app',
    measurementId: 'G-Q0C1KYGWYB',
  );

}